---
permissions:
  id-token: write
  contents: write

name: Create release or publish to pnpm reusable workflow
on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      os:
        description: The operating system to run the workflow on
        required: false
        type: string
        default: ubuntu-latest
      node:
        description: The node version to use when creating the release
        required: false
        type: string
        default: "18"
      repository:
        description: The repository to use when creating the release
        required: true
        type: string
    secrets:
      token:
        required: true
      npm_token:
        required: true

jobs:
  release:
    if: ${{ github.repository == inputs.repository && contains('refs/heads/master', github.ref)}}
    runs-on: ${{ inputs.os }}
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - name: 📦 Check out the codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ⚙️ Setup node ${{ inputs.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node }}
          registry-url: "https://registry.npmjs.org/"

      - name: 📥 Monorepo install
        uses: annminn104/gh-actions/actions/pnpm/install/action.yml@master
        with:
          enable-corepack: false
          cache-node-modules: true

      - name: 🦋 Create release pull request or publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore: update versions"
          title: "chore: update versions"
          cwd: ${{ github.workspace }}
          publish: pnpm run cs:publish
          version: pnpm run cs:version
          setupGitUser: true
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
          NPM_TOKEN: ${{ secrets.npm_token }}
          NPM_CONFIG_PROVENANCE: true

      - name: Push changes to changeset-release branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.token }}@github.com/${{ github.repository }}.git
          git push origin HEAD:changeset-release/master --force

        env:
          HOME: ${{ github.workspace }}
          GITHUB_TOKEN: ${{ secrets.token }}
          NPM_TOKEN: ${{ secrets.npm_token }}
